 INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 1, 5, SYSDATE - 5, 5000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 5, CURRENT_BIDDER = '도니', CURRENT_BID_AMOUNT = 5000
		WHERE AUCTION_ID = 1;
		
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 2, 4, SYSDATE - 5, 5000);
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 2, 3, SYSDATE - 4, 6000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 3, CURRENT_BIDDER = '박거성', CURRENT_BID_AMOUNT = 6000
		WHERE AUCTION_ID = 2;
		
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 3, 4, SYSDATE - 5, 5000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 4, CURRENT_BIDDER = '노긍정', CURRENT_BID_AMOUNT = 5000
		WHERE AUCTION_ID = 3;
		
		
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 6, 5, SYSDATE - 5, 5000);
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 6, 3, SYSDATE - 4, 6000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 3, CURRENT_BIDDER = '박거성', CURRENT_BID_AMOUNT = 6000
		WHERE AUCTION_ID = 6;
		
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 7, 4, SYSDATE - 5, 5000);
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 7, 3, SYSDATE - 4, 6000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 3, CURRENT_BIDDER = '박거성', CURRENT_BID_AMOUNT = 6000
		WHERE AUCTION_ID = 7;
		
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 8, 4, SYSDATE - 5, 5000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 4, CURRENT_BIDDER = '노긍정', CURRENT_BID_AMOUNT = 5000
		WHERE AUCTION_ID = 8;
		
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 11, 5, SYSDATE - 5, 5000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 5, CURRENT_BIDDER = '도니', CURRENT_BID_AMOUNT = 5000
		WHERE AUCTION_ID = 11;
		
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 12, 4, SYSDATE - 5, 5000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 4, CURRENT_BIDDER = '노긍정', CURRENT_BID_AMOUNT = 5000
		WHERE AUCTION_ID = 12;
		
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 13, 4, SYSDATE - 5, 5000);
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 13, 3, SYSDATE - 4, 6000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 3, CURRENT_BIDDER = '박거성', CURRENT_BID_AMOUNT = 6000
		WHERE AUCTION_ID = 13;	
		







-- 입찰중

INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 16, 5, SYSDATE - 5, 5000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 5, CURRENT_BIDDER = '도니', CURRENT_BID_AMOUNT = 5000
		WHERE AUCTION_ID = 16;
		
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 17, 4, SYSDATE - 5, 5000);
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 17, 3, SYSDATE - 4, 6000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 3, CURRENT_BIDDER = '박거성', CURRENT_BID_AMOUNT = 6000
		WHERE AUCTION_ID = 17;
		
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 18, 4, SYSDATE - 5, 5000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 4, CURRENT_BIDDER = '노긍정', CURRENT_BID_AMOUNT = 5000
		WHERE AUCTION_ID = 18;
		
		
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 21, 5, SYSDATE - 5, 5000);
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 21, 3, SYSDATE - 4, 6000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 3, CURRENT_BIDDER = '박거성', CURRENT_BID_AMOUNT = 6000
		WHERE AUCTION_ID = 21;
		
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 22, 4, SYSDATE - 5, 5000);
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 22, 3, SYSDATE - 4, 6000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 3, CURRENT_BIDDER = '박거성', CURRENT_BID_AMOUNT = 6000
		WHERE AUCTION_ID = 22;
		
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 23, 4, SYSDATE - 5, 5000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 4, CURRENT_BIDDER = '노긍정', CURRENT_BID_AMOUNT = 5000
		WHERE AUCTION_ID = 23;
		
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 26, 5, SYSDATE - 5, 5000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 5, CURRENT_BIDDER = '도니', CURRENT_BID_AMOUNT = 5000
		WHERE AUCTION_ID = 26;
		
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 27, 4, SYSDATE - 5, 5000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 4, CURRENT_BIDDER = '노긍정', CURRENT_BID_AMOUNT = 5000
		WHERE AUCTION_ID = 27;
		
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 28, 4, SYSDATE - 5, 5000);
INSERT INTO auction_bid ( AUCTION_ID, BIDDER_ID, BIDDING_DATE, BID_AMOUNT )
        VALUES ( 28, 3, SYSDATE - 4, 6000);
UPDATE AUCTION_ITEM SET CURRENT_BIDDER_ID = 3, CURRENT_BIDDER = '박거성', CURRENT_BID_AMOUNT = 6000
		WHERE AUCTION_ID = 28;	
		
COMMIT;